baseURL = "https://docs.ipfs.io"
relativeURLs = true
languageCode = "en"
DefaultContentLanguage = "en"
title = "IPFS Documentation"
staticDir = ["static", "build"]
googleAnalytics = "UA-96910779-6"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

[blackfriday]
hrefTargetBlank = true

[params]
editURL = "https://github.com/ipfs/docs/tree/master/content/"
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[menu]

[[menu.main]]
identifier = "introduction"
name = "介绍"
weight = 1

[[menu.main]]
identifier = "guides"
name = "指南"
weight = 2

[[menu.main]]
identifier = "reference"
name = "参考"
weight = 3

[[menu.main]]
identifier = "community"
name = "社区"
weight = 4

[[menu.reference]]
identifier = "api"
name = "命令与 API"
weight = 4
[[menu.reference]]
parent = "api"
name = "JS 和 Go 程序库"
url = "https://github.com/ipfs/interface-ipfs-core/tree/master/SPEC"
weight = 30

[[menu.reference]]
identifier = "go_implementation"
name = "Go 版实现"
weight = 5
[[menu.reference]]
parent = "go_implementation"
name = "go-ipfs 核心 API"
url = "/go/pkg/go-ipfs/core/coreapi"
weight = 10
[[menu.reference]]
parent = "go_implementation"
name = "go-ipfs Coreiface API" # 和下面都是 Go 语言相关概念吗？不知道怎么翻译
url = "/go/pkg/go-ipfs/core/coreapi/interface"
weight = 11
[[menu.reference]]
parent = "go_implementation"
name = "go-ipfs Core options API"
url = "/go/pkg/go-ipfs/core/coreapi/interface/options"
weight = 12
[[menu.reference]]
parent = "go_implementation"
name = "go-ipfs-api 参考"
url = "/go/pkg/go-ipfs-api"
weight = 30

[[menu.reference]]
identifier = "js_implementation"
name = "JS 版实现"
weight = 5
[[menu.reference]]
parent = "js_implementation"
name = "js-ipfs"
url = "https://github.com/ipfs/js-ipfs"
weight = 10
[[menu.reference]]
parent = "js_implementation"
name = "js-ipfs-api"
url = "https://github.com/ipfs/js-ipfs-api"
weight = 20

[[menu.reference]]
identifier = "specs"
name = "规范和计划"
weight = 6
[[menu.reference]]
parent = "specs"
name = "IPFS 白皮书"
url = "https://github.com/ipfs/ipfs/blob/master/papers/ipfs-cap2pfs/ipfs-p2p-file-system.pdf"
weight = 10
[[menu.reference]]
parent = "specs"
name = "IPFS 规范"
url = "https://github.com/ipfs/specs"
weight = 20
[[menu.reference]]
parent = "specs"
name = "直到 1.0.0 的路线图"
url = "https://github.com/ipfs/ipfs/blob/master/REQUIREMENTS.md"
weight = 30
[[menu.reference]]
parent = "specs"
name = "各实现版本的状态"
url = "https://github.com/ipfs/ipfs/blob/master/IMPLEMENTATION_STATUS.md"
weight = 40
[[menu.reference]]
parent = "specs"
name = "RFC 列表"
title = "“变更请求”” (RFC) 是对协议、程序库接口和社区流程进行较大变更的提案"
url = "https://github.com/ipfs/rfcs"
weight = 50

[[menu.guides]]
identifier = "guides"
name = "指南"
weight = 3
[[menu.guides]]
identifier = "examples"
name = "示例"
weight = 4
[[menu.guides]]
parent = "guides"
name = "复制大量数据"
url = "https://github.com/ipfs/archives/tree/master/tutorials/replicating-large-datasets"
weight = 3
[[menu.guides]]
parent = "guides"
name = "传输文件"
url = "https://github.com/ipfs/go-ipfs/blob/master/docs/file-transfer.md"
weight = 2
[[menu.guides]]
parent = "guides"
name = "浏览器中的地址"
url = "https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md"
weight = 4
[[menu.guides]]
parent = "guides"
name = "交互式教程"
url = "https://proto.school/#/tutorials"
weight = 5
[[menu.guides]]
parent = "examples"
name = "js-ipfs 示例"
url = "https://github.com/ipfs/js-ipfs/tree/master/examples"

[[menu.community]]
identifier = "applications"
name = "应用"
weight = 8
[[menu.community]]
parent = "applications"
name = "IPFS 集群"
title = "管理多个机器上的 IPFS 节点集群，以共享存储资源。"
url = "http://cluster.ipfs.io"
weight = 10
[[menu.community]]
parent = "applications"
name = "IPFS 桌面客户端"
title = "运行 IPFS 节点的跨平台图形应用。"
url = "https://github.com/ipfs-shipyard/ipfs-desktop"
weight = 20
[[menu.community]]
parent = "applications"
name = "IPFS 伴侣"
title = "使网页中的 IPFS 资源安全可用的浏览器扩展。"
url = "https://github.com/ipfs-shipyard/ipfs-companion"
weight = 30
[[menu.community]]
parent = "applications"
name = "IPFS Pack"
title = "把大量数据包装为适合 IPFS 的标准格式。"
url = "https://github.com/ipfs/ipfs-pack"
weight = 40

[[menu.community]]
identifier = "community"
name = "社区"
weight = 9
[[menu.community]]
parent = "community"
name = "讨论/支持论坛"
url = "https://discuss.ipfs.io/"
weight = 10
[[menu.community]]
parent = "community"
name = "IRC"
url = "/community/irc/"
weight = 20
[[menu.community]]
parent = "community"
name = "研讨"
url = "https://github.com/ipfs/notes"
weight = 30
[[menu.community]]
parent = "community"
name = "活动日历"
url = "https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com"
weight = 40
[[menu.community]]
parent = "community"
name = "社区工具"
url = "https://github.com/ipfs/community/"
weight = 50
[[menu.community]]
parent = "community"
name = "项目管理"
url = "https://github.com/ipfs/pm/"
weight = 60
[[menu.community]]
parent = "community"
name = "博客"
url = "https://ipfs.io/blog/"
weight = 70
[[menu.community]]
parent = "community"
name = "Youtube"
url = "https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew"
weight = 80
[[menu.community]]
parent = "community"
name = "Twitter (@IPFSbot)"
url = "https://twitter.com/IPFSbot"
weight = 90
[[menu.community]]
parent = "community"
name = "Awesome IPFS"
url = "https://awesome.ipfs.io/"
[[menu.community]]
parent = "community"
name = "IPFS 公共存档"
title = "保存有价值的公共数据的存档的社区项目。"
url = "https://archives.ipfs.io"
[[menu.community]]
parent="community"
name = "常见问题"
url = "https://discuss.ipfs.io/c/help/Old-FAQ"

[[menu.community]]
identifier = "contribute"
name = "参与进来"
weight = 10
[[menu.community]]
parent = "contribute"
name = "GitHub (IPFS)"
url = "https://github.com/ipfs/ipfs"
weight = 10
[[menu.community]]
parent = "contribute"
name = "GitHub (docs)"
url = "https://github.com/ipfs/docs"
weight = 20
[[menu.community]]
parent = "contribute"
name = "贡献指南"
url = "https://github.com/ipfs/community/blob/master/CONTRIBUTING.md"
weight = 30
[[menu.community]]
parent = "contribute"
name = "行为守则"
url = "https://github.com/ipfs/community/blob/master/code-of-conduct.md"
weight = 40
[[menu.community]]
parent = "contribute"
name = "Go 风格指南"
url = "https://github.com/ipfs/community/blob/master/CONTRIBUTING_GO.md"
weight = 50
[[menu.community]]
parent = "contribute"
name = "JS 风格指南"
url = "https://github.com/ipfs/community/blob/master/CONTRIBUTING_JS.md"
weight = 60

[[menu.community]]
identifier = "related"
name = "相关项目"
[[menu.community]]
parent = "related"
name = "Libp2p"
url = "http://libp2p.io"
weight = 1
[[menu.community]]
parent = "related"
name = "Multiformats"
url = "https://multiformats.io"
weight = 2
[[menu.community]]
parent = "related"
name = "IPLD"
url = "https://ipld.io"
weight = 3
[[menu.community]]
parent = "related"
name = "ProtoSchool"
url = "https://proto.school/"
